update

diff --git a/bin/fdup b/bin/fdup
--- a/bin/fdup
+++ b/bin/fdup
@@ -2,6 +2,34 @@
 # Usage: fdup [root dir] [target dir]
 
 set -e
+
+# type="f"
+#
+# while (( "$#" )); do
+#   case "$1" in
+#     --type)
+#       if [ -n "$2" ] && { [ "$2" = "d" ] || [ "$2" = "f" ]; }; then
+#         type=$2
+#         shift 2
+#       else
+#         echo "Error: Argument for $1 is missing or invalid. Use 'd' for directories or 'f' for files." >&2
+#         exit 1
+#       fi
+#       ;;
+#     --) # end argument parsing
+#       shift
+#       break
+#       ;;
+#     -*|--*=) # unsupported flags
+#       echo "Error: Unsupported flag $1" >&2
+#       exit 1
+#       ;;
+#     *) # preserve positional arguments
+#       break
+#       ;;
+#   esac
+# done
+#
 rpbin="realpath"
 if [[ "$OSTYPE" == "darwin"* ]]; then
   rpbin="grealpath"
